Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,76 +1,35 @@
-name: ci
-
+name: checkov
 on:
+  pull_request:
   push:
     branches:
-    - "*"  # run for branches
-    tags:
-    - "*"  # run for tags
-  pull_request:
-    branches:
-    - "*"  # run for branches
-    tags:
-    - "*"  # run for tags
-
+      - main    
 jobs:
-  test:
-    runs-on: ubuntu-latest
-    env:
-      GROUP: weaveworksdemos 
-      COMMIT: ${{ github.sha }}
-      REPO: front-end
+  scan:
+    runs-on: ubuntu-latest 
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for GitHub/codeql-action/upload-sarif to upload SARIF results
+     
     steps:
     - uses: actions/checkout@v2
-
-    #
-    #
-    # Set up  node
-    - uses: actions/setup-node@v1
+    
+    - name: Run checkov 
+      id: checkov
+      uses: bridgecrewio/checkov-action@master
       with:
-        node-version: '4.x'
-
-    #
-    #
-    # Install dependencies
-    - run: npm install
-
-    #
-    #
-    # Run node tests in docker image
-    - name: Test image
-      env:
-        DOCKER_BUILDKIT: 1
-      run: make test
-
-    #
-    #
-    # Build docker image for service
-    - name: Build docker image
-      uses: docker/build-push-action@v1
+        directory: code/
+        #soft_fail: true
+        #api-key: ${{ secrets.BC_API_KEY }}
+      #env:
+        #PRISMA_API_URL: https://api4.prismacloud.io
+        
+    - name: Upload SARIF file
+      uses: GitHub/codeql-action/upload-sarif@v3
+      
+      # Results are generated only on a success or failure
+      # this is required since GitHub by default won't run the next step
+      # when the previous one has failed. Alternatively, enable soft_fail in checkov action.
+      if: success() || failure()
       with:
-        push: false
-        repository: ${{ env.GROUP }}/${{ env.REPO }}
-        tag_with_ref: true
-        tag_with_sha: true
-        tags: ${{ github.sha }}
-
-    #
-    #
-    # Run simple test against built container
-    - name: Test docker image
-      env:
-        DOCKER_BUILDKIT: 1
-      run: ./test/container.sh
-
-    #
-    #
-    # Push to dockerhub
-    - name: Push to Docker Hub
-      uses: docker/build-push-action@v1
-      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
-      with:
-        username: ${{ secrets.DOCKER_USER }}
-        password: ${{ secrets.DOCKER_PASS }}
-        repository: ${{ env.GROUP }}/${{ env.REPO }}
-        tag_with_ref: true
-        tag_with_sha: true
+        sarif_file: results.sarif
